cmd.align("polymer and name CA and (ligase_lig)","polymer and name CA and (aa)",quiet=0,object="aln_ligase_lig_to_aa",reset=1)
cmd.align("polymer and name CA and (target_lig)","polymer and name CA and (aa)",quiet=0,object="aln_target_lig_to_aa",reset=1)
cmd.select('sele','none')
cmd.select('sele',"byresi((((sele) or byresi((ligase_lig`707))) and not ((byresi((ligase_lig`707))) and byresi(sele))))",enable=1)
cmd.copy_to("aa","sele",zoom=0,quiet=0)
cmd.select('sele','none')
cmd.select('sele',"byresi((((sele) or byresi((target_lig`832))) and not ((byresi((target_lig`832))) and byresi(sele))))",enable=1)
cmd.copy_to("aa","sele",zoom=0,quiet=0)
cmd.save("aligned.pdb")
